FROM python:3.10-slim

WORKDIR /app

COPY portfolio_django/requirements.txt ./
RUN pip install --no-cache-dir -r requirements.txt

COPY portfolio_django/ .

EXPOSE 8000

ENV DJANGO_SETTINGS_MODULE=portfolio_django.settings
ENV PYTHONUNBUFFERED=1

CMD ["python", "manage.py", "runserver", "0.0.0.0:8000"]
